networks:
  default:
    driver: bridge

services:
  api1:
    build: .
    depends_on:
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"
    environment:
      CACHE_ADDRESS: cache
      CACHE_PORT: 6379
      DATABASE_HOST: database
      DATABASE_NAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      PORT: 8080
    expose:
      - "8080"
    hostname: api1
    # ports:
    #   - "8001:8080"

  api2:
    build: .
    depends_on:
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"
    environment:
      CACHE_ADDRESS: cache
      CACHE_PORT: 6379
      DATABASE_HOST: database
      DATABASE_NAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      PORT: 8080
    expose:
      - "8080"
    hostname: api2
    # ports:
    #   - "8002:8080"

  cache:
    command: ["redis-server", "/etc/redis/redis.conf"]
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"
    expose:
      - "6379"
    hostname: cache
    image: redis:latest
    ports:
      - "8004:6379"
    volumes:
      - ./scripts/redis/:/etc/redis/

  database:
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "1.25GB"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 15s
      timeout: 25s
    hostname: database
    image: postgres:latest
    ports:
      - "8003:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./scripts/postgres/postgresql.sql:/docker-entrypoint-initdb.d/postgresql.sql
      - ./scripts/postgres/postgresql.conf:/etc/postgresql/postgresql.conf

  nginx:
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.25GB"
    hostname: api
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./scripts/nginx/:/etc/nginx/

version: "3.5"

volumes:
  postgres-db:
